theme: jekyll-theme-minimal
title: Md Raza Usmani
description: A proactive & creative 28-year-old graduate student from Dhaka, Bangladesh, with 1+ year experience working with Design & Animation with great attention to detail.
