theme: jekyll-theme-minimal
title: Md Raza Usmani
description: CV of Md Raza Usmani
body: A proactive & creative 26-year-old graduate student from Dhaka, Bangladesh, with 1+ year experience working with Design & Animation with great attention to detail.
